### ISSUE TITLE
[Bug]:  Virtual buttons in pyLoxone never triggered

### ISSUE THREAD

**Issue by workeyman** [JoDehli/PyLoxone#294]
### Describe the bug

Unfortunately, the virtual buttons no longer work. They are recognized and listed by pyLoxone, but when I press the button in Loxone, it is not recognized by pyLoxone. However, I can see in the Loxone Config that the button is triggered (duration: 0.3s).
<img width="373" alt="Bildschirmfoto 2024-08-06 um 07 46 20" src="https://github.com/user-attachments/assets/1cae60ad-d76d-4043-bdb2-a0cff81bd690">

### Firmware of your Miniserver

15.0.5.29

### HomeAssistant install method

Installed "Home Assistant Operating System" by raspberry pi imager.

### Version of HomeAssistant

2024.7.4
Supervisor 2024.06.2

### Version of Pyloxone

0.6.11

### Update pyloxone

yes

### Log

No errors

**Comment by JoDehli** [comment]
@gigatexel another problem here....

**Comment by workeyman** [comment]
I had to replace buttons with switches in Loxone Config so that the control at least works again. push buttons no longer seem to work.

**Comment by gigatexel** [comment]
> I had to replace buttons with switches in Loxone Config so that the control at least works again. push buttons no longer seem to work.

Can you post a screenshot of the detailed config in Loxone that no longer works?

**Comment by workeyman** [comment]
At the very top of this issue, I attached a picture... Aren't you referring to that information? Is there another way to display the information from the virtual button?

**Comment by gigatexel** [comment]
Can you replace the code in custom_components/loxone/button.py with this code: https://github.com/gigatexel/PyLoxone/blob/gigatexel-patch-button/custom_components/loxone/button.py

**Comment by workeyman** [comment]
Now pyLoxone has an error and can't start:
`ImportError: cannot import name 'get_or_create_device' from 'custom_components.loxone.helpers' (/config/custom_components/loxone/helpers.py)`

**Comment by gigatexel** [comment]
Are you on the latest version? Can you post the contents of helpers.py on pastebin?

**Comment by workeyman** [comment]
I have updatet pyLoxone in Home Assistant, so i'm using the version (tag: 0.6.11 - newest version).
So helpers.py is exactly the same as here (i have compared both files):
https://github.com/JoDehli/PyLoxone/blob/0.6.11/custom_components/loxone/helpers.py

**Comment by gigatexel** [comment]
Can you try again: https://github.com/gigatexel/PyLoxone/blob/gigatexel-patch-button/custom_components/loxone/button.py

**Comment by workeyman** [comment]
I need to look into this when I have time. Sorry, but we use pyLoxone here at the company for voice announcements in a shared office when the doorbell rings, and I can't test this now. Otherwise, it will just confuse the employees. 

Sorry that I can't test this right away.

**Comment by gigatexel** [comment]
No problem. I removed pyLoxone en tested with this code, now works on my setup.

**Comment by JoDehli** [comment]
@workeyman should be fixed in the newest version

**Comment by workeyman** [comment]
I updated pyLoxone to version 0.6.12 and restarted Home Assistant. Unfortunately, it still doesn't seem to pass the event from Loxone to pyLoxone. When I press the button in the Loxone app, the pressing of the virtual button is not passed on to pyLoxone/Home Assistant. I never see the virtual button being triggered.

Thank you anyway very much for your help. 

<img width="623" alt="Bildschirmfoto 2024-08-07 um 06 26 26" src="https://github.com/user-attachments/assets/f5da5927-5a42-425f-8e83-c6a428a67446">

**Comment by gigatexel** [comment]
Ok, now it's clear to me. Your issue is "the other way around". When you press the button in Loxone Config or in the app, you don't see that in Home Assistant.

That is in fact not possible. A Home Assistant button is stateless. It cannot be "On" or "Off"
See also: https://developers.home-assistant.io/docs/core/entity/button/

**Comment by gigatexel** [comment]
I understand your issue, but this is not standard HA behaviour. The button state does not change (cause it does not have a state), so it does not get logged.
You do get a log entry when you push the button in HA, because HA logs the button being pushed for a button - not the state change.

However, I did mange to create a workaround: https://github.com/gigatexel/PyLoxone/blob/gigatexel-button-event/custom_components/loxone/button.py

Can you test this? It creates a logbook entry when a button is pushed in Loxone.

**Comment by workeyman** [comment]
I will check this as soon as I have time and am alone in the company where I use this Home Assistant instance.

**Comment by JoDehli** [comment]
@workeyman the button worked only the state was not reported when triggered from loxone. In my opinion this is not a big deal. I added it anyway.

**Comment by workeyman** [comment]
All right, thank you very much for your help!
